/* This is the grader file for pset62. You may look, but DO NOT EDIT THIS FILE.
 * Even though this is not the master file that I will use to give your work a 
 * score, do not edit this file, as you won't be able to accurately predict 
 * your grade.
 */

public class grademy_pset62{
    public static void main(String[] args){
		int totalScore = 0;
		String op = gmh.goip("pset62.java");
		String cd = gmh.gcip("pset62.java");
		String[] strArr = {"I", "love", "git"};
		int[] fibArr = new int[50];
		fibArr[0] = 0;
		fibArr[1] = 1;
		//sum is 1,599.064
		double[] dbArr = {50.7, 302.23, 1.0, 1245.134};
		double[] dbArr2 = new double[20];
		//sum is -1497.28765
		double[] dbArr3 = {-542.3, 34.0, -988.98765};
		
		/* 1) Declare and initialize a String array to contain the 
		 * values "I", "love", and "git", in that order. You 
		 * MUST call this array strArr.
		*/
		if(gmh.a7fn(cd, "String[] strArr", 1)){
			System.out.println("1) 1/1");
			totalScore += 1;
		}
		/* 2) Declare and initialize an int array of length 50. Then set its first 
		 * and second values to 1. This array MUST be called fibArr. Don't change 
		 * any of the other 48 values.
		*/
		if(gmh.a7fn(cd, "int[] fibArr = new int[50]", 1)){
			System.out.println("2) 1/1");
			totalScore += 1;
		}
		/* 3) Declare and initialize a double array to contain the values 50.7, 
		 * 302.23, 1.0, and 1245.134, in that order.You MUST call your array dbArr.
		*/
		if(gmh.a7fn(cd, "double[] dbArr", 1)){
			System.out.println("3) 1/1");
			totalScore += 1;
		}
		/* 4) Write a public static method called printStringArray that 
	 	* prints out the contents of strArr, each on their own line.
		*/
		if(gmh.a5fn(op, "I\nlove\ngit")){
			System.out.println("4) 1/1");
			totalScore += 1;
		}
		/* 5) Write a public static method called sumDoubleArray that sums up all of the 
	 	* values in a double array and returns the sum.
		*/
		if(pset62.sumDoubleArray(dbArr) == 1599.064){
			System.out.println("5) +1/3");
			totalScore += 1;
		}
		if(pset62.sumDoubleArray(dbArr2) == 0.0){
			System.out.println("5) +1/3");
			totalScore += 1;
		}
		if(pset62.sumDoubleArray(dbArr3) == -1497.28765){
			System.out.println("5) +1/3");
			totalScore += 1;
		}
		/* 6) Write a public static method called fibFifty that takes an int array as its sole
	 	* parameter and edits the 3rd through 50th spots in it to contain the 3rd-50th 
	 	* fibonacci numbers. You can assume that the array it takes will always have values
	 	* of 1 in their first two spots (which are the first two fibonacci numbers) 
		* and 0s in the 3rd through 50th spots. fibFifty must return an int array with the first 
	 	* 50 fibonacci numbers.*/
		int[] resArr = pset62.fibFifty(fibArr);
		if(resArr[4] == 3){
			System.out.println("6) +1/3");
			totalScore += 1;
		}
		if(resArr[8] == 21){
			System.out.println("6) +1/3");
			totalScore += 1;
		}
		if(resArr[40] == 102334155){
			System.out.println("6) +1/3");
			totalScore += 1;
		}
		/* 7) Call your printStringArray method on strArr.*/
		if(gmh.a7fn(cd, "printStringArray(strArr)", 1)){
			System.out.println("7) 1/1");
			totalScore += 1;
		}
		/* 8) Call your sumDoubleArray method on dbArr.*/
		if(gmh.a7fn(cd, "sumDoubleArray(dbArr)", 1)){
			System.out.println("8) 1/1");
			totalScore += 1;
		}
		/* 9) Call your fibFifty method on intArr */
		if(gmh.a7fn(cd, "fibFifty(fibArr)", 1)){
			System.out.println("9) 1/1");
			totalScore += 1;
		}
		System.out.println("Total: " + totalScore + "/12");
    }
}
