/* This is the grader file for pset64. You may look, but DO NOT EDIT THIS FILE.
 * Even though this is not the master file that I will use to give your work a 
 * score, do not edit this file, as you won't be able to accurately predict 
 * your grade.
 */

public class grademy_pset64{
    public static void main(String[] args){
		int totalScore = 0;
		/* 1) Write a method called median that returns the median value in the array. 
		If the length of the array is odd, the median is the value in the center 
		of the array. If the length of the array is even, the median is the 
		average of the two numbers in the center. You may assume the array 
		passed into this method will never be empty. */
		int[] test11 = {12, 75, 3, 17, 65, 22};
		int[] test12 = {12, 75, 3, 17, 65, 22, 105};
		int[] test13 = {-5};
		if(pset64.median(test11) == 10){
			System.out.println("1) +1/3");
			totalScore += 1;
		}
		if(pset64.median(test12) == 17){
			System.out.println("1) +1/3");
			totalScore += 1;
		}
		if(pset64.median(test13) == -5){
			System.out.println("1) +1/3");
			totalScore += 1;
		}
		/* 2) Write a method called findMultipleOfThree that returns the last value 
		in the array that is a multiple of 3. If no multiple of 3 exists in the 
		array, return -1. For example, in the array [4, 7, 9, 7, 12] the last 
		multiple of three is 12 */
		int[] test21 = {76, 75, 3, 17, 12, 22, 7};
		int[] test22 = {85, 39, 30, 12, 40, 33333333};
		int[] test23 = {-3, 38, 31, 13, 40, 34};
		if(pset64.findMultipleOfThree(test21) == 10){
			System.out.println("2) +1/3");
			totalScore += 1;
		}
		if(pset64.findMultipleOfThree(test22) == 10){
			System.out.println("2) +1/3");
			totalScore += 1;
		}
		if(pset64.findMultipleOfThree(test23) == 10){
			System.out.println("2) +1/3");
			totalScore += 1;
		}
		/* 3) Complete the getStudentImprovement method in the Student class. */
		/* 4) Then, complete the getMostImprovedStudent method in the Classroom 
		class. Call the getStudentImprovement method to help you. */
		Classroom c = new Classroom(3);
        Student ada = new Student("Ada", "Lovelace", 12);
        ada.addExamScore(44);
        ada.addExamScore(65);
        ada.addExamScore(77);
        Student alan = new Student("Alan", "Turing", 11);
        alan.addExamScore(38);
        alan.addExamScore(24);
        alan.addExamScore(31);
		Student max = new Student("Max", "Effort", 9);
        max.addExamScore(90);
        max.addExamScore(91);
        max.addExamScore(92);
        max.addExamScore(21);
        max.addExamScore(40);
        c.addStudent(ada);
        c.addStudent(alan);
        c.addStudent(max);
        if(ada.getStudentImprovement() == 23){
			System.out.println("3) +1/3");
			totalScore += 1;
		}
        if(alan.getStudentImprovement() == -7){
			System.out.println("3) +1/3");
			totalScore += 1;
		}
        if(max.getStudentImprovement() == -50){
			System.out.println("3) +1/3");
			totalScore += 1;
		}
        if(c.getMostImprovedStudent().getName().equals("Ada")){
			System.out.println("4) +1/1");
			totalScore += 1;
		}
		System.out.println("Total: " + totalScore + "/10");
    }
}
